### ISSUE TITLE
Install fails due to PortalockerFiles dependency

### ISSUE THREAD

**Issue by philipbelesky** [evandrocoan/BufferScroll#1]
Hi!

Upon installing (by adding the repo to Package Control manually) installing the package then seems to fail with:

```
Package Control: The dependency 'PortalockerFiles' is not currently installed; installing...
Package Control: The dependency 'PortalockerFiles' is not available
Package Control: The dependency 'PortalockerFiles' could not be installed or updated
```

Looking around pip there is a `Portalocker` but not a `PortalockerFiles` I assume this is the problem?

**Comment by evandrocoan** [comment]
The latest version of the logging module uses new dependencies which are not available as dependency on Package Control yet. These are the pull requests:

1. https://github.com/wbond/package_control_channel/pull/6918 Added the portalock dependency to repository/dependencies.json
1. https://github.com/wbond/package_control_channel/pull/6919 Added the dependency concurrent-log-handler to dependencies.json
1. Also, there is a renaming pending on: https://github.com/wbond/package_control_channel/pull/6916 Renamed the dependency PythonDebugTools to DebugTools

Until they are merged, you can install them locally by manually installing the dependencies:
```
git clone https://github.com/evandrocoan/DebugTools
git clone https://github.com/evandroforks/PortalockerFiles
git clone https://github.com/evandroforks/ConcurrentLogHandler
```
And running the Package Control commands `Install Local Dependency` and `Satisfy Dependencies`

**Comment by philipbelesky** [comment]
Ah, I misunderstood dependencies.json and thought it would be pulling from pip. Thanks!

**Comment by evandrocoan** [comment]
Yeah, I would like that too. But I think it is not currently possible because Sublime Text uses Python 3.3 and pip for Python 3.3 is not supported anymore. So, until Sublime Text upgrades its internal python, only then, Package Control can be updated to install dependencies with `pip` directly.

Sublime Text does not come with `pip` since the beginning because only recently it started loading python dependencies from the folder `lib/python3.3` on its installation folder and now there is no `pip` for it.
